[colors.bright]
black = "0x576466"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x9db500"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0xb58900"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x839496"

[font]
size = 7

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraLight"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B"
key = "LBracket"
mods = "Control"

[mouse]
hide_when_typing = false

[window]
title = "Terminal"
