[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'neoclide/coc-highlight'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'josa42/coc-go'
build = 'yarn install --frozen-lockfile'
on_ft = ['go']

[[plugins]]
repo = 'clangd/coc-clangd'
build = 'yarn install --frozen-lockfile'
on_ft = ['c', 'cpp']
hook_add = '''
  hi link cStorageClass Statement 
  hi link cppStructure Statement
  hi link cppType Statement
'''

[[plugins]]
repo = 'voldikss/coc-cmake'
build = 'yarn install --frozen-lockfile'
on_ft = ['cmake']

[[plugins]]
repo = 'fannheyward/coc-rust-analyzer'
build = 'yarn install --frozen-lockfile'
on_ft = ['rust']
hook_add = '''
  hi rustModPathSep guifg=#FFFFFF
  hi rustOperator guifg=#FFFFFF
  hi link rustStorage Statement
  hi rustDecNumber guifg=#B4CDA8
'''

[[plugins]]
repo = 'neoclide/coc-json'
build = 'yarn install --frozen-lockfile'
on_ft = ['json']

[[plugins]]
repo = 'neoclide/coc-tsserver'
build = 'yarn install --frozen-lockfile'
on_ft = ['typescript', 'javascript', 'typescript.jsx', 'typescript.tsx']

[[plugins]]
repo = 'neoclide/coc-prettier'
build = 'yarn install --frozen-lockfile'
on_ft = ['typescript', 'javascript', 'typescript.jsx', 'typescript.tsx']

[[plugins]]
repo = 'josa42/coc-go'
build = 'yarn install --frozen-lockfile'
on_ft = ['go']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
hook_add = '''
  hi link tomlTableArray Statement
  hi link tomlTable Statement
'''
