[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'neoclide/coc-highlight'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'josa42/coc-go'
build = 'yarn install --frozen-lockfile'
on_ft = ['go']

[[plugins]]
repo = 'clangd/coc-clangd'
build = 'yarn install --frozen-lockfile'
on_ft = ['c', 'cpp']
hook_source = '''
  hi link cStorageClass Statement 
  hi link cppStructure Statement
  hi link cppType Statement
'''

[[plugins]]
repo = 'voldikss/coc-cmake'
build = 'yarn install --frozen-lockfile'
on_ft = ['cmake']

[[plugins]]
repo = 'kawaemon/coc-rust-analyzer'
build = 'yarn install --frozen-lockfile'
on_ft = ['rust']
hook_source = '''
  hi rustModPathSep guifg=#FFFFFF
  hi rustOperator guifg=#FFFFFF
  hi link rustStorage Statement
  hi rustDecNumber guifg=#B4CDA8
  hi link rustBoolean Statement
  hi link rustSelf Statement
'''


[[plugins]]
repo = 'neoclide/coc-json'
build = 'yarn install --frozen-lockfile'
on_ft = ['json']
hook_source = '''
  hi link jsonQuote String
  hi link jsonKeyword Identifier
  hi jsonBraces guifg=#FFFFFF
'''


[[plugins]]
repo = 'neoclide/coc-tsserver'
build = 'yarn install --frozen-lockfile'
on_ft = ['typescript', 'javascript', 'typescript.jsx', 'typescript.tsx']
hook_source = '''
  hi link typescriptStorageClass Statement
  hi typescriptEndColons guifg=#FFFFFF
  hi typescriptBraces guifg=#FFFFFF
  hi typescriptParens guifg=#FFFFFF
  hi typescriptOpSymbols guifg=#FFFFFF
'''

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
depends = ['leafgarland/typescript-vim']
on_ft = ['typescript', 'typescript.tsx', 'typescript.jsx']
hook_source = '''
  hi tsxTag guifg=#FFFFFF
  hi tsxTagName guifg=#E06C75
  hi link tsxCloseTagName tsxTagName
  hi link tsxAttrib Identifier
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescript.tsx', 'typescript.jsx']

[[plugins]]
repo = 'neoclide/coc-prettier'
build = 'yarn install --frozen-lockfile'
on_ft = ['typescript', 'javascript', 'typescript.jsx', 'typescript.tsx']


[[plugins]]
repo = 'neoclide/coc-css'
build = 'yarn install --frozen-lockfile'
on_ft = ['css', 'scss', 'sass']
hook_source = '''
  hi cssBraces guifg=#FFFFFF
'''

[[plugins]]
repo = 'neoclide/coc-html'
build = 'yarn install --frozen-lockfile'
on_ft = ['html']

[[plugins]]
repo = 'josa42/coc-go'
build = 'yarn install --frozen-lockfile'
on_ft = ['go']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
hook_source = '''
  hi link tomlTableArray Statement
  hi link tomlTable Statement
'''

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_source = '''
  hi link mkdHeading Identifier
'''

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_source = '''
  let g:previm_open_cmd = 'chromium'
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'andys8/vim-elm-syntax.git'
on_ft = ['elm']
hook_source = '''
  hi link elmImport Statement
  hi link elmTypedef Statement
  hi link elmAlias Statement
  hi elmBraces guifg=#FFFFFF
  hi elmDelimiter guifg=#FFFFFF
  hi elmOperator guifg=#FFFFFF
'''

[[plugins]]
repo = 'neoclide/coc-python'
build = 'yarn install --frozen-lockfile'
on_ft = ['python']

[[plugins]]
repo = 'vim-python/python-syntax'
on_ft = ['python']
hook_source = '''
  let g:python_highlight_all = 1
  hi pythonOperator guifg=#FFFFFF
'''

[[plugins]]
repo = 'neoclide/coc-yaml'
build = 'yarn install --frozen-lockfile'
on_ft = ['yaml']
hook_source = '''
  hi yamlKeyValueDelimiter guifg=#FFFFFF
'''

