command_timeout = 50

[aws]
disabled = true

[gcloud]
disabled = true

[character]
success_symbol = '>'
error_symbol = '[>](red)'
vimcmd_symbol = '[v](green)'
vimcmd_replace_one_symbol = 'v'
vimcmd_replace_symbol = '[v](purple)'
vimcmd_visual_symbol = '[v](yellow)'
