[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'josa42/coc-go'
build = 'yarn install --frozen-lockfile'
on_ft = ['go']

[[plugins]]
repo = 'clangd/coc-clangd'
build = 'yarn install --frozen-lockfile'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'voldikss/coc-cmake'
build = 'yarn install --frozen-lockfile'
on_ft = ['cmake']

[[plugins]]
repo = 'fannheyward/coc-rust-analyzer'
build = 'yarn install --frozen-lockfile'
on_ft = ['rust']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_source = '''
  let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'neoclide/coc-json'
build = 'yarn install --frozen-lockfile'
on_ft = ['json']


[[plugins]]
repo = 'neoclide/coc-tsserver'
build = 'yarn install --frozen-lockfile'
on_ft = ['typescript', 'javascript', 'typescript.jsx', 'typescript.tsx']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
depends = ['leafgarland/typescript-vim']
on_ft = ['typescript', 'typescript.tsx', 'typescript.jsx']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescript.tsx', 'typescript.jsx']

[[plugins]]
repo = 'neoclide/coc-prettier'
build = 'yarn install --frozen-lockfile'
on_ft = ['typescript', 'javascript', 'typescript.jsx', 'typescript.tsx']

[[plugins]]
repo = 'neoclide/coc-css'
build = 'yarn install --frozen-lockfile'
on_ft = ['css', 'scss', 'sass']

[[plugins]]
repo = 'neoclide/coc-html'
build = 'yarn install --frozen-lockfile'
on_ft = ['html']

[[plugins]]
repo = 'josa42/coc-go'
build = 'yarn install --frozen-lockfile'
on_ft = ['go']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_source = '''
  let g:previm_open_cmd = 'chromium'
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'andys8/vim-elm-syntax.git'
on_ft = ['elm']

[[plugins]]
repo = 'neoclide/coc-python'
build = 'yarn install --frozen-lockfile'
on_ft = ['python']

[[plugins]]
repo = 'vim-python/python-syntax'
on_ft = ['python']
hook_source = '''
  let g:python_highlight_all = 1
'''

[[plugins]]
repo = 'neoclide/coc-yaml'
build = 'yarn install --frozen-lockfile'
on_ft = ['yaml']

[[plugins]]
repo = 'scalameta/coc-metals'
build = 'yarn install --frozen-lockfile'
on_ft = ['scala']

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']
