[[plugins]]
repo = "Shougo/dein.vim"
hook_add = "command! -nargs=0 DeinRecache :call dein#recache_runtimepath()"

[[plugins]]
repo = "kyazdani42/nvim-web-devicons"
hook_add = "lua require('nvim-web-devicons').setup()"

[[plugins]]
repo = "kdheepak/tabline.nvim"
hook_add = "lua require('tabline').setup({ enable = true })"

[[plugins]]
repo = "nvim-lualine/lualine.nvim"
hook_add = "lua require('lualine').setup({ theme = 'solarized_dark' })"

[[plugins]]
repo = "windwp/nvim-ts-autotag"

[[plugins]]
repo = "lukas-reineke/indent-blankline.nvim"
hook_add = """
lua <<EOF
    require('indent_blankline').setup({
        show_current_context = true,
    })
EOF
"""

[[plugins]]
repo = "easymotion/vim-easymotion"
hook_add = "nmap ss <Plug>(easymotion-s2)"

[[plugins]]
repo = "nvim-treesitter/playground"

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
depends = ["windwp/nvim-ts-autotag", "nvim-treesitter/playground"]
hook_post_update = "TSUpdate"
hook_add = """
hi! clear TSError
hi TSError gui=underline guifg=#dc322f

lua <<EOF
require("nvim-treesitter.configs").setup({
    ensure_installed = "all",
    highlight = { enable = true },
    indent = { enable = true },
    autotag = { enable = true },
    playground = { enable = true },
})
EOF
"""

[[plugins]]
repo = "kyazdani42/nvim-tree.lua"
hook_add = """
command! -nargs=0 Tree :NvimTreeToggle

lua <<EOF
vim.g.nvim_tree_icons = {
    git_icons = {
       unstaged = "",
       staged = "",
       unmerged = "",
       renamed = "➜",
       untracked = "",
       deleted = "",
       ignored = "",
    }
}

vim.g.nvim_tree_show_icons = {
    git = 1,
    folders = 1,
    folder_arrows = 1,
    files = 0,
}

vim.g.nvim_tree_special_files = {}

require("nvim-tree").setup({
    open_on_setup = true,
    view = {
        auto_resize = true,
        mappings = {
            -- disable default 's' key mapping (opens file with system default editor)
            list = { { key = "s" } }
        }
    }
})
EOF
"""

[[plugins]]
repo = "kdheepak/lazygit.nvim"
hook_add = "command! -nargs=0 Lg :LazyGit"

[[plugins]]
repo = "lewis6991/gitsigns.nvim"
hook_add = """
lua <<EOF
    require('gitsigns').setup()
    vim.api.nvim_create_user_command(
        "Blame",
        function() vim.cmd("Gitsigns toggle_current_line_blame") end,
        {}
    )
EOF
"""

[[plugins]]
repo = "ishan9299/nvim-solarized-lua"
hook_add = "colorscheme solarized-flat"

[[plugins]]
repo = "junegunn/fzf"
build = "./install --all"
merged = 0

[[plugins]]
repo = "junegunn/fzf.vim"
depends = "fzf"
hook_add = "command! -nargs=0 F :Files"
