[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline#extensions#tabline#enabled = 1
  let g:airline_powerline_fonts = 1
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'
hook_add = '''
lua <<EOF
  require'nvim-treesitter.configs'.setup {
      ensure_installed = "maintained",
      highlight = {
        enable = true
      }
    }
EOF
'''

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'kawaemon/nord-vim'
branch = "feat/support-treesitter"
hook_add = '''
  syntax on
  colorscheme nord
'''

[[plugins]]
repo = 'junegunn/fzf'
build = "./install --all"
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = "fzf"
hook_add = '''
  command! -nargs=0 F :Files
'''

[[plugins]]
repo = 'wakatime/vim-wakatime'

