[[plugins]]
repo = "neovim/nvim-lspconfig"

[[plugins]]
repo = "hrsh7th/cmp-buffer"

[[plugins]]
repo = "hrsh7th/cmp-path"

[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp"

[[plugins]]
repo = "L3MON4D3/LuaSnip"

[[plugins]]
repo = "saadparwaiz1/cmp_luasnip"
depends = ["L3MON4D3/LuaSnip"]

[[plugins]]
repo = "hrsh7th/cmp-cmdline"

[[plugins]]
repo = "hrsh7th/nvim-cmp"
depends = [
    "neovim/nvim-lspconfig",
    "hrsh7th/cmp-buffer",
    "hrsh7th/cmp-path",
    "hrsh7th/cmp-nvim-lsp",
    "saadparwaiz1/cmp_luasnip",
    "L3MON4D3/LuaSnip",
    "hrsh7th/cmp-cmdline",
]
hook_add = """
command! -nargs=0 Lsp :lua require("klsp").setup()
"""
