[[plugins]]
repo = "hrsh7th/cmp-buffer"

[[plugins]]
repo = "hrsh7th/cmp-path"

[[plugins]]
repo = "hrsh7th/nvim-cmp"
depends = ["hrsh7th/cmp-buffer", "hrsh7th/cmp-path"]
hook_add = """
set completeopt=menu,menuone,noselect

lua <<EOF

local cmp = require("cmp")

cmp.setup({
    sources = cmp.config.sources({}, {
        { name = "buffer" },
    }),

    mapping = {
        ["<Tab>"] = cmp.mapping(cmp.mapping.select_next_item(), { "i", "s" }),
        ["<S-Tab>"] = cmp.mapping(cmp.mapping.select_prev_item(), { "i", "s" })
    }
})

cmp.setup.cmdline("/", { sources = { { name = "buffer" } } })
cmp.setup.cmdline(":", { sources = { { name = "path" } } })

EOF
"""

[[plugins]]
repo = "osyo-manga/vim-precious"
depends = ["Shougo/context_filetype.vim"]


[[plugins]]
repo = "Shougo/context_filetype.vim"

